import '../styles/globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next 베타버전...',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children } : { children: React.ReactNode }) {

  return (
    <html lang="ko">
      <body className={inter.className}>
      {children}
      </body>
    </html>
    )
}
