import '../styles/globals.css';
import { Inter } from 'next/font/google';
import Login from './components/Login';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next 베타버전...',
  description: 'Generated by create next app',
}

export default function RootLayout({ children } : { children: React.ReactNode }) {
  const isLogin:boolean = true;

  
  return (
    <html lang="ko">
      <body className={inter.className}>
      {isLogin ? 
        <Login isLogin={isLogin} />
        :
        <div>{children}</div>
      }
      </body>
    </html>
  )
}
