import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";
import styles from "../app/styles/page.module.css";
import "../app/styles/globals.css";

// components
import Header from "./components/Header";

// library
import Recoil from "./store/Recoil";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
   return (
      <html lang="en">
         <link
            rel="icon"
            href="/favicon.ico"
            sizes="any"
         />
         <body className={inter.className}>
            <Recoil>
               <Header />
               <main className={styles.main}>{children}</main>
            </Recoil>
         </body>
      </html>
   );
}
