import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from "./page.module.css";
import React from "react";
import "./globals.css";

// library
import Recoil from "./store/Recoil";
import { useRecoilValue } from "recoil";
import { loginStore } from "./store/Recoil";

// components
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
   console.log(useRecoilValue(loginStore));

   return (
      <html lang="en">
         <link
            rel="icon"
            href="/favicon.ico"
            sizes="any"
         />
         <body className={inter.className}>
            <Header />
            <main className={styles.main}>
               <Recoil>{children}</Recoil>
            </main>
         </body>
      </html>
   );
}
