import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// library
import Recoil from "./store/Recoil";

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
   // if (typeof window !== "undefined") {
   //    const userInfo = localStorage.getItem("userInfo");
   //    console.log(userInfo);
   // }

   return (
      <html lang="en">
         <link
            rel="icon"
            href="/favicon.ico"
            sizes="any"
         />
         <body className={inter.className}>
            <Recoil>{children}</Recoil>
         </body>
      </html>
   );
}
